### ISSUE TITLE
Advertisement

### ISSUE THREAD

**Issue by ghost** [Codetoil/HaveASolTime#12]
![Screenshot 2024-05-01 191018](https://github.com/Codetoil/HaveASolTime/assets/166317640/74d6c369-26aa-41fd-a587-826805530f05)

**Comment by reverentfeynmen** [comment]
Advertisement 
![vector-download-download-button-illustration-data-3142962059](https://github.com/Codetoil/HaveASolTime/assets/166317640/10c65e2d-a8db-4000-a0aa-ec29d3e04615)

**Comment by reverentfeynmen** [comment]
Advertisement 
![Screenshot 2024-04-04 114728](https://github.com/Codetoil/HaveASolTime/assets/166317640/0a771edc-45db-4b7b-b6c0-b4898b526bfd)

**Comment by reverentfeynmen** [comment]
Advertisement 
![Screenshot 2024-05-21 185458](https://github.com/Codetoil/HaveASolTime/assets/166317640/040d81f4-b16e-463a-9d4f-2decf28b38d6)

**Comment by Codetoil** [comment]
That would be CurseForge, not me. I don't control any of the adds that are on the download page.
