### ISSUE TITLE
[CRASH] Crash when clicking on Jupiter.

### ISSUE THREAD

**Issue by ghost** [Codetoil/HaveASolTime#13]
![Screenshot 2024-05-04 115857](https://github.com/Codetoil/HaveASolTime/assets/166317640/748879fa-48e1-43cf-84da-b84c98097c43)
![GAME CRASHED!!!!!!!](https://github.com/Codetoil/HaveASolTime/assets/166317640/d39f2800-20c6-459a-92e3-b9c57edaef30)

**Comment by Codetoil** [comment]
That doesn't seem like something from my mod.
