### ISSUE TITLE
[BUG] Can't go to The Sun.

### ISSUE THREAD

**Issue by ghost** [Codetoil/HaveASolTime#3]
![Uploading Screenshot 2024-05-21 201501.png…]()

**Comment by Codetoil** [comment]
No idea what you are talking about, the image didn't load.

**Comment by Codetoil** [comment]
Plus it works on my end

**Comment by ghost** [comment]
> No idea what you are talking about, the image didn't load.

Okay here. 
![Screenshot 2024-05-21 201501](https://github.com/Codetoil/haveasoltime/assets/166317640/0a4a001a-c71a-44e4-a691-e097fd5edc13)

**Comment by ghost** [comment]
> Plus it works on my end

But thats not fair that it doesn't work on mine.

**Comment by ghost** [comment]
You ToTheStars mod does nothing.

**Comment by Codetoil** [comment]
ToTheStars is a library and coremod. It's not intended to have any features. HaveASolTime, which depends on ToTheStars, is what implements landable Sol.
