### ISSUE TITLE
[GLITCH] Sun Plasma texture is missing.

### ISSUE THREAD

**Issue by ghost** [Codetoil/HaveASolTime#4]
![Uploading Screenshot 2024-05-21 201742.png…]()

**Comment by Codetoil** [comment]
I'm well aware about this. Maybe I should take another look at my fluid rendering code.

**Comment by Codetoil** [comment]
![2024-05-22_21 23 42](https://github.com/Codetoil/haveasoltime/assets/32802727/0192fc83-7b52-4417-bd31-5d7be00b19d7)
Actually, it's fixed on my end.
