### ISSUE TITLE
[ERROR] Requires mods that don't exist.

### ISSUE THREAD

**Issue by ghost** [Codetoil/HaveASolTime#5]
![Screenshot 2024-05-21 201951](https://github.com/Codetoil/HaveASolTime/assets/166317640/30e2a2cb-ffcd-4c9a-9e55-b1bbad219d6f)

**Comment by reverentfeynmen** [comment]
![Uploading Screenshot 2024-05-21 202451.png…]()

**Comment by ghost** [comment]
![Screenshot 2024-05-21 202451](https://github.com/Codetoil/HaveASolTime/assets/166317640/b747ca94-6dbf-42b3-8646-c74851449c02)

**Comment by ghost** [comment]
![Screenshot 2024-05-21 203048](https://github.com/Codetoil/HaveASolTime/assets/166317640/3edafdbf-8246-4b13-adef-052ac845b3c5)

**Comment by Codetoil** [comment]
As far as I know, HaveASolTime should only require ToTheStars...

**Comment by Codetoil** [comment]
Fake
