### ISSUE TITLE
[ERROR] Requires Crashma.

### ISSUE THREAD

**Issue by ghost** [Codetoil/HaveASolTime#7]
![Screenshot 2024-05-21 201951](https://github.com/Codetoil/HaveASolTime/assets/166317640/4f2a6081-42df-4b6c-86a9-63e411e704e1)

**Comment by ghost** [comment]
![Screenshot 2024-05-22 151727](https://github.com/Codetoil/HaveASolTime/assets/166317640/761dae76-29d0-4bb0-b6c4-5e8bafa68fcb)

**Comment by Codetoil** [comment]
Fake
