### ISSUE TITLE
[ERROR] Microsoft Bing is a dependency.

### ISSUE THREAD

**Issue by ghost** [Codetoil/HaveASolTime#8]
![Screenshot 2024-05-21 201951](https://github.com/Codetoil/HaveASolTime/assets/166317640/4524d7a2-5aa6-4b8f-93ad-1dc378d9895b)
![microsoft-bing-chat_mgqf](https://github.com/Codetoil/HaveASolTime/assets/166317640/f32a0f39-132d-41ba-9c9f-1bf31c939808)

**Comment by Codetoil** [comment]
Fake

**Comment by ghost** [comment]
Joke.
