### ISSUE TITLE
[BUG] NPE and major glitch with Galaxy Map.

### ISSUE THREAD

**Issue by ghost** [Codetoil/HaveASolTime#9]
![52169135-a5c8fb80-272b-11e9-8943-acb302cc0e39](https://github.com/Codetoil/HaveASolTime/assets/166317640/a6d00ae3-af17-4bcc-8edb-40d6f5b0d78f)

**Comment by reverentfeynmen** [comment]
10 Seconds later folowing the NPE. 
![Screenshot 2024-04-19 205456](https://github.com/Codetoil/HaveASolTime/assets/166317640/e7e34bd5-06af-40ab-b5f1-51005e7af37e)

**Comment by ghost** [comment]
10 Seconds later folowing the NPE. 
![Screenshot 2024-04-14 193147](https://github.com/Codetoil/HaveASolTime/assets/166317640/01ce7535-db5b-4d23-b42c-79312d148eb0)

**Comment by Codetoil** [comment]
Wow that looks messed up. What other coremods are you using?

**Comment by ghost** [comment]
> Wow that looks messed up. What other coremods are you using?

Optifine

**Comment by Codetoil** [comment]
Well, Optifine is known to cause issues with other mods, so try removing it.

**Comment by ghost** [comment]
This keeps happening every time I try to load HavASolTime. 
![Screenshot 2024-05-21 200938](https://github.com/Codetoil/haveasoltime/assets/166317640/e0410cf6-d4d6-4120-a562-2b5c2d1bcd34)

**Comment by Codetoil** [comment]
Can you send the logs and/or the crash report.
